### ISSUE TITLE
test:ci does not run integration tests

### ISSUE THREAD

**Issue by jelisejev** [ctco-dev/koa-graphql-ts-template#16]

**Comment by trioletas** [comment]
doesn't work:
```
λ npm run test:ci

> koa-graphql-ts-template@0.1.0 test:ci C:\SRDEV\git\github\koa-graphql-ts-template
> npm run test:all -- --config jest.ci.config.js


> koa-graphql-ts-template@0.1.0 test:all C:\SRDEV\git\github\koa-graphql-ts-template
> jest --projects src src/graphql "--config" "jest.ci.config.js"

 PASS  src\services\__tests__\sum.test.ts
 PASS  src\services\__tests__\sum.test.ts

Test Suites: 2 passed, 2 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        2.839s
Ran all test suites in 2 projects.

=============================== Coverage summary ===============================
Statements   : 100% ( 6/6 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 2/2 )
Lines        : 100% ( 5/5 )
================================================================================
```

`joke.test.ts` is not run

**Comment by aeldar** [comment]
there is an option conflict.
If we use `--project` option for _jest_, then for every project jest runs and uses the `jest.config.json` located in that same project directory. But if we use `--config` option in addition, then all `--project` options seems ignored.

**Comment by trioletas** [comment]
Good point, any ideas how to achieve the desired effect? I kinda suck at `jest`, would be nice if you could assist us here @aeldar

**Comment by trioletas** [comment]
We want to make sure that `test:ci` run unit **and** integration test with coverage/reporting features enabled.
At the same time it should be possible to run integration or unit tests without the reporting capabilities.
- test:ci -> unit/int/coverage
- test -> unit
- test:integration -> integration

**Comment by aeldar** [comment]
I added another pull request for this issue, probably, a more appropriate solution of the problem #19.
